### ISSUE TITLE
Error adding new Entites

### ISSUE THREAD

**Issue by BillGatesPriv** [hhimanshu/spring-boot-liquibase#3]
Hey,

i encountered a problem inserting new "Authors" into the database. It occured when i used a different id, but 1-5 as they are already set in advance. Otherwise an error "ID = null constraint violation" appeared.

The reason for this beeing is the @GeneratedValue(strategy=GenerationType.IDENTITY) as they rely on the database to set the id. In order to fix it, i gave the id-column the value "autoIncrement=true".

+ Thank you for your example helped me a lot understanding liquibase!

**Comment by BillGatesPriv** [comment]
Edit: Same should be true for the books aswell

**Comment by hhimanshu** [comment]
Wonderful, do you mind opening up a pull request with this change? This will help other learners as well
